import Head from 'next/head'
import React from 'react'
import { useTitle } from 'src/hooks'

export default function Heading() {
  const title = useTitle()

  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by Daffa Akbar" />
      <link rel="icon" href="/skull.ico" />
    </Head>
  )
}
